export const MANAGE_FILM_REQUEST = 'MANAGE_FILM_REQUEST';
export const MANAGE_FILM_SUCCESS = 'MANAGE_FILM_SUCCESS';
export const MANAGE_FILM_FAIL = 'MANAGE_FILM_FAIL';

export const DELETE_FILM_REQUEST = 'DELETE_FILM_REQUEST';
export const DELETE_FILM_SUCCESS = 'DELETE_FILM_SUCCESS';
export const DELETE_FILM_FAIL = 'DELETE_FILM_FAIL';
