export const DETAIL_FILM_REQUEST = 'DETAIL_FILM_REQUEST';
export const DETAIL_FILM_SUCCESS = 'DETAIL_FILM_SUCCESS';
export const DETAIL_FILM_FAIL = 'DETAIL_FILM_FAIL';

export const UPDATE_FILM_REQUEST = 'UPDATE_FILM_REQUEST';
export const UPDATE_FILM_SUCCESS = 'UPDATE_FILM_SUCCESS';
export const UPDATE_FILM_FAIL = 'UPDATE_FILM_FAIL';

