export const MANAGE_CINEMA_REQUEST = 'MANAGE_CINEMA_REQUEST';
export const MANAGE_CINEMA_SUCCESS = 'MANAGE_CINEMA_SUCCESS';
export const MANAGE_CINEMA_FAIL = 'MANAGE_CINEMA_FAIL';

export const DETAIL_CINEMA_REQUEST = 'DETAIL_CINEMA_REQUEST';
export const DETAIL_CINEMA_SUCCESS = 'DETAIL_CINEMA_SUCCESS';
export const DETAIL_CINEMA_FAIL = 'DETAIL_CINEMA_FAIL';

export const ADD_NEW_CALENDAR_REQUEST = 'ADD_NEW_CALENDAR_REQUEST';
export const ADD_NEW_CALENDAR_SUCCESS = 'ADD_NEW_CALENDAR_SUCCESS';
export const ADD_NEW_CALENDAR_FAIL = 'ADD_NEW_CALENDAR_FAIL';
