export const MANAGE_USER_REQUEST = 'MANAGE_USER_REQUEST';
export const MANAGE_USER_SUCCESS = 'MANAGE_USER_SUCCESS';
export const MANAGE_USER_FAIL = 'MANAGE_USER_FAIL';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';
